package com.example.mentimeter.Service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.cloud.vertexai.VertexAI;
import com.google.cloud.vertexai.api.GenerateContentResponse;
import com.google.cloud.vertexai.generativeai.GenerativeModel;
import com.google.cloud.vertexai.generativeai.ResponseHandler;
import com.example.mentimeter.Model.Quiz; // Import your Quiz model
import com.example.mentimeter.DTO.AiQuizFromTextRequest;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
public class GeminiAiService {

    @Value("${gcp.project.id}")
    private String projectId;

    @Value("${gcp.location}")
    private String location;

    private final ObjectMapper objectMapper = new ObjectMapper();

    // --- NEW METHOD ---
    public Quiz generateQuizFromText(AiQuizFromTextRequest request) throws IOException {
        String prompt = buildQuizPromptFromText(request.getContent(), request.getNumQuestions(), request.getDifficulty());

        try (VertexAI vertexAi = new VertexAI(projectId, location)) {
            String modelName = "gemini-2.5-flash"; // Or your preferred model
            GenerativeModel model = new GenerativeModel(modelName, vertexAi);
            GenerateContentResponse response = model.generateContent(prompt);
            String rawJsonResponse = ResponseHandler.getText(response);

            // --- Parse the JSON string directly into a Quiz object ---
            try {

                rawJsonResponse = rawJsonResponse.replace("```json", "").replace("```", "").trim();

                // Parse into Quiz object
                Quiz generatedQuiz = objectMapper.readValue(rawJsonResponse, Quiz.class);

                // You might want to set default/placeholder values if AI omits them
                if (generatedQuiz.getTitle() == null || generatedQuiz.getTitle().isBlank()) {
                    generatedQuiz.setTitle("AI Generated Quiz");
                }
                // Important: Don't trust AI for username, set it later based on logged-in user
                generatedQuiz.setUsername(SecurityContextHolder.getContext().getAuthentication().getName());
                generatedQuiz.setShareCode(null); // Ensure these aren't set by AI
                generatedQuiz.setShared(false);
                generatedQuiz.setId(null); // ID should be generated by DB

                return generatedQuiz;
            } catch (Exception e) {
                System.err.println("Error parsing Quiz JSON response from Gemini: " + rawJsonResponse);
                System.err.println("Parser Exception: " + e.getMessage());
                throw new IOException("Failed to parse valid Quiz JSON from AI response.", e);
            }
            // --- End JSON Parsing ---

        } catch (Exception e) {
            System.err.println("Error calling Gemini API: " + e.getMessage());
            throw new IOException("Failed to generate quiz from Gemini API", e);
        }
    }

    // In GeminiAiService.java

// ... (your existing generateQuizFromText method stays the same) ...

    /**
     * Builds the AI prompt to GENERATE a new quiz based on a TOPIC.
     */
    private String buildQuizPromptFromText(String content, int numQuestions, String difficulty) {

        // The "content" variable now holds the topic name (e.g., "CyberSecurity")
        String topic = content;

        // This is the new prompt template
        String promptTemplate =
                "Your task is to generate a new quiz. The user has provided the following **topic**: '%s'.\n\n" +

                        "Generate exactly %d multiple-choice questions *about* this topic." +
                        "The difficulty level for the questions should be '%s'.\n" +

                        // This is the new, important guardrail
                        "**Important**: Do NOT generate questions *about* the provided text (e.g., 'What topic was provided?'). " +
                        "You must generate questions that *test a user's knowledge* of that topic.\n\n" +

                        "The output must be a single JSON object matching this exact structure:\n" +
                        "{\n" +
                        "  \"title\": \"(Generate a concise title for a quiz about the topic, e.g., 'Cybersecurity Fundamentals')\",\n" +
                        "  \"questionList\": [\n" +
                        "    {\n" +
                        "      \"text\": \"(A question about the topic, e.g., 'What is a DDoS attack?')\",\n" +
                        "      \"options\": [\"Option A\", \"Option B\", \"Option C\", \"Option D\"],\n" +
                        "      \"correctAnswerIndex\": (Integer index 0-3)\n" +
                        "    }\n" +
                        "    // ... (repeat for %d questions)\n" +
                        "  ]\n" +
                        "}\n" +
                        "Do NOT include 'id', 'username', 'shareCode', or 'isShared' fields. " +
                        "Ensure the JSON is valid. Provide only the JSON object, with no introductory text or markdown formatting.";

        // Return the formatted string
        return String.format(
                promptTemplate,
                topic,          // %s (e.g., "CyberSecurity")
                numQuestions,   // %d (number of questions)
                difficulty,     // %s (e.g., "Hard")
                numQuestions    // %d (for the comment)
        );
    }

    // Keep your original generateQuizQuestions method if needed for other features
    // public List<Question> generateQuizQuestions(AiQuizRequest request) throws IOException { ... }
}